name: xscalenvs
channels:
  - conda-forge
  - defaults
dependencies:
  - iopath
  - jinja2
  - matplotlib
  - numpy
  - python 
  - tqdm
  - pip:
    - open3d
    - opencv-python
    - pillow
    - pyparsing
    - scikit-image
    - scikit-learn
    - scipy
    - tensorboard
    - tensorboardx
    - tinycudann
    - trimesh
